services:
  mft:
    image: default-route-openshift-image-registry.apps.68f62d11926501b4673f4b0b.am1.techzone.ibm.com/mft/stt-activetransfer:1.0.0-mysql
    container_name: mft
    restart: always
    ports:
      - "35555:5555"      
      - "10000-10010:10000-10010" # For the listeners
    volumes:
      - ./mft/application.properties:/opt/softwareag/IntegrationServer/application.properties
    env_file:
      - .env
    healthcheck:
      interval: 5s
      retries: 24
      test: ["CMD-SHELL", "curl -o /dev/null -s -w '%{http_code}' http://localhost:5555 | grep -qE '^(200|3[0-9]{2})$'"]
