apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcc-sa

---

apiVersion: batch/v1
kind: Job
metadata:
  name: dcc-job
  labels:
    app: dcc
spec:
  backoffLimit: 0  
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: dcc
    spec:
      serviceAccountName: dcc-sa
      restartPolicy: Never  
      # imagePullSecrets:
      #   - name: regcred
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dcc
          image: stt-activetransfer-dcc:20251129
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_ACTION
              value: "create"
          volumeMounts:
            - name: secrets
              mountPath: /opt/softwareag/common/auth/db
              readOnly: true
            - name: tmp                   
              mountPath: /tmp
            - name: dcc-logs              
              mountPath: /opt/softwareag/common/db/logs
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            #readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: secrets
          secret:
            secretName: dcc-secrets
            defaultMode: 0444
        - name: tmp
          emptyDir: {}                    
        - name: dcc-logs
          emptyDir: {}